version: '3.1'

services:
  php8:
    build: .
    container_name: php7-apache
    image: php:8.2-apache
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html/
      # - ./configuration/vhosts/enabled:/etc/apache2/sites-enabled
      # - ./configuration/vhosts/available:/etc/apache2/sites-available
