FROM mariadb:jammy

ENV MARIADB_USER=example-user
ENV MARIADB_PASSWORD=user-password
ENV MARIADB_ROOT_PASSWORD=root-secret-password
ENV MARIADB_DATABASE=world-db

CMD [myql]

# docker --name world-db -p 3360:3306 -env 