version: '3.8'

services:
  app:
    restart: 'yes'
    image: php:7
    command: php -S 0.0.0.0:8000 /app/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app