# Utiliza una imagen base mínima
FROM alpine:latest

# Instala las dependencias necesarias
# RUN apk add --no-cache <nombre-de-tus-dependencias>

# Copia solo los archivos necesarios a la imagen
# COPY <directorio-local> /<directorio-en-la-imagen>

# Establece el directorio de trabajo
# WORKDIR /<directorio-en-la-imagen>

# Especifica el comando por defecto al ejecutar el contenedor
# CMD ["<comando-por-defecto>"]
