version: "3.3"
services:
  resapp:
    build: .
    container_name: residence
    hostname: residence
    # restart: always
    ports:
      - '5000:80'
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
    networks:
      - default
networks:
  default:
    external: true
    name: mysql_develoop

